using System.Collections.Generic;
using System.IO;
using Unity.Scenes;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using Zori.Entities.CharacterController2D.Authoring;
using Zori.Entities.CharacterController2D.Samples;
using PhysicsBody2DAuthoring = Zori.Entities.Physics2D.Authoring.PhysicsBody2DAuthoring;
using PhysicsBody2DMotionType = Zori.Entities.Physics2D.Authoring.PhysicsBody2DMotionType;
using PhysicsShape2DAuthoring = Zori.Entities.Physics2D.Authoring.PhysicsShape2DAuthoring;
using PhysicsShape2DKind = Zori.Entities.Physics2D.PhysicsShape2DKind;

namespace Zori.Entities.CharacterController2D.Samples.Editor
{
    /// <summary>
    /// Click-free, reproducible authoring of the side-scroller sample scene — the same proven pattern the controller's
    /// behavioural-gate fixtures use (<c>CharacterFixtureBuilder</c>), rather than hand-authored fragile <c>.unity</c>
    /// YAML. It builds a parent scene (the one you open, carrying the SubScene + the follow camera) and a SubScene
    /// child (the baked ECS content: the config singleton, the character, the static world — floor, a step within and
    /// one over the step limit, a slope within and one over the slope limit — a pushable dynamic crate, and a
    /// <see cref="TrackedTransform2D"/> moving platform).
    ///
    /// <para>Run via the menu (Tools/Zori/Build Side-Scroller Sample Scene) or
    /// <c>-executeMethod Zori.Entities.CharacterController2D.Samples.Editor.SideScrollerSceneBuilder.Build</c>. The
    /// scene writes into the sample's own <c>Scenes/</c> folder so the importable sample carries it; on import the
    /// whole <c>Samples~/SideScrollerCharacter</c> tree (including the built scenes) copies into <c>Assets/Samples/</c>.</para>
    /// </summary>
    public static class SideScrollerSceneBuilder
    {
        const float FloorTopY = 0f;
        const float CharacterHalf = 0.5f; // the box character is 1x1 (full extents 2*half).
        const float MaxStepHeight = 0.5f;
        const float MaxSlopeDeg = 60f;

        /// <summary>
        /// The <c>Scenes/</c> directory next to this builder, resolved from the builder's OWN asset path so the scene
        /// is written wherever the sample currently lives — the importable copy under <c>Assets/Samples/…</c> after a
        /// user imports the sample (where <c>AssetDatabase</c> works), and equally any other location it is dropped.
        /// A hard-coded <c>Samples~/</c> path would NOT work: a tilde folder is not an <c>AssetDatabase</c> path
        /// (Unity ignores <c>Samples~</c> entirely), so <c>SaveScene</c> / <c>LoadAssetAtPath&lt;SceneAsset&gt;</c>
        /// against it would fail. The scene is therefore a GENERATED artifact, produced by running this builder once
        /// after import — the same model the controller's test fixtures use (their <c>.unity</c> files are generated by
        /// <c>CharacterFixtureBuilder</c>, not hand-authored sources).
        /// </summary>
        static string SceneDir
        {
            get
            {
                // Find this builder's own MonoScript asset path (its …/Editor folder), then its sibling …/Scenes. The
                // script name is unique in the project, so FindAssets returns exactly this script.
                string[] guids = AssetDatabase.FindAssets("SideScrollerSceneBuilder t:MonoScript");
                string scriptPath = guids.Length > 0
                    ? AssetDatabase.GUIDToAssetPath(guids[0])
                    : null;
                if (string.IsNullOrEmpty(scriptPath))
                {
                    // Not yet under an AssetDatabase path (e.g. still in Samples~ before import) — nothing to build.
                    throw new System.InvalidOperationException(
                        "SideScrollerSceneBuilder is not under an AssetDatabase path; import the sample into "
                            + "Assets/Samples/ first, then run the builder.");
                }

                string editorDir = Path.GetDirectoryName(scriptPath).Replace('\\', '/');
                string sampleRoot = Path.GetDirectoryName(editorDir).Replace('\\', '/');
                return sampleRoot + "/Scenes";
            }
        }

        static string ParentScene => SceneDir + "/SideScrollerSample.unity";
        static string ChildScene => SceneDir + "/SideScrollerSample_Sub.unity";

        [MenuItem("Tools/Zori/Build Side-Scroller Sample Scene")]
        public static void Build()
        {
            string sceneDir = SceneDir;
            if (!AssetDatabase.IsValidFolder(sceneDir))
            {
                string parent = Path.GetDirectoryName(sceneDir).Replace('\\', '/');
                AssetDatabase.CreateFolder(parent, "Scenes");
            }

            BuildChild();
            BuildParent();

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("Side-Scroller sample scene built at " + ParentScene);
        }

        // The SubScene child: the baked ECS content.
        static void BuildChild()
        {
            var child = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            // The opt-in config singleton — without this the sample's systems are inert (design §8).
            var config = new GameObject("SampleConfig");
            config.AddComponent<SideScrollerSampleConfigAuthoring>();

            // --- Static world ----------------------------------------------------------------------------------

            // A long flat floor; its top surface sits at FloorTopY.
            AddStaticBox(new Vector2(6f, FloorTopY - 0.5f), new Vector2(60f, 1f), "Floor");

            // Step within the limit (top 0.3 <= 0.5): the character steps up onto it. Left face at X = 4.
            AddStaticBox(new Vector2(7f, 0.3f - 1f), new Vector2(6f, 2f), "StepLow_top0.3");

            // Step over the limit (top 0.9 > 0.5): the character is blocked, slides into it like a wall. Sits on top of
            // the low step's right end so the walk hits it after the low step. Left face at X = 10.
            AddStaticBox(new Vector2(13f, 0.9f - 1.5f), new Vector2(6f, 3f), "StepHigh_top0.9");

            // Slope within the limit (30deg < 60deg): the character climbs it. A rotated ramp butted at the lip.
            AddRamp(lipX: 18f, lipY: FloorTopY, lengthAlong: 14f, slopeDeg: 30f, "SlopeWithinLimit_30deg");

            // Slope over the limit (75deg > 60deg): the character cannot stand, slides down. A steep ramp further along.
            AddRamp(lipX: 30f, lipY: FloorTopY, lengthAlong: 8f, slopeDeg: 75f, "SlopeOverLimit_75deg");

            // --- Dynamic pushable crate ------------------------------------------------------------------------

            // A 1x1 dynamic box the character pushes. Gravity ON so it rests on the floor; it is a getting-started
            // crate, not the gate's gravity-off probe. Explicit mass so the push is mass-scaled predictably.
            AddPushableCrate(new Vector2(-3f, FloorTopY + 0.5f + 0.02f), new Vector2(1f, 1f), mass: 1f, "Crate");

            // --- Moving platform -------------------------------------------------------------------------------

            // A wide thin kinematic platform the character can ride, oscillating in X. Placed in a gap to the left of
            // the floor's left end so it is visibly a separate ride. Top surface a little above the floor.
            AddMovingPlatform(new Vector2(-12f, FloorTopY + 1f - 0.25f), new Vector2(4f, 0.5f), halfExtentX: 4f, speedX: 3f, "MovingPlatform");

            // --- Character -------------------------------------------------------------------------------------

            // A box-proxy character (1x1) with step handling on, spawned on the flat floor. Box proxy because the gate
            // verified step-up holds a stable stand for a box (a circle catches the step's top-left corner).
            AddCharacter(new Vector3(0f, FloorTopY + CharacterHalf + 0.05f, 0f));

            EditorSceneManager.MarkSceneDirty(child);
            EditorSceneManager.SaveScene(child, ChildScene);
        }

        // The parent scene: the SubScene reference + a 2D orthographic follow camera.
        static void BuildParent()
        {
            var parent = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            var subSceneGo = new GameObject("SideScrollerSample SubScene");
            var subScene = subSceneGo.AddComponent<SubScene>();
            subScene.SceneAsset = AssetDatabase.LoadAssetAtPath<SceneAsset>(ChildScene);
            subScene.AutoLoadScene = true;

            // The follow camera (orthographic), looking down +Z at the 2D plane.
            var camGo = new GameObject("Main Camera");
            var cam = camGo.AddComponent<Camera>();
            cam.orthographic = true;
            cam.orthographicSize = 7f;
            cam.transform.position = new Vector3(0f, 2f, -10f);
            cam.clearFlags = CameraClearFlags.SolidColor;
            cam.backgroundColor = new Color(0.12f, 0.13f, 0.18f, 1f);
            camGo.AddComponent<SideScrollerFollowCamera>();
            camGo.tag = "MainCamera";

            EditorSceneManager.MarkSceneDirty(parent);
            EditorSceneManager.SaveScene(parent, ParentScene);

            RegisterSceneInBuildSettings(ParentScene);
            RegisterSceneInBuildSettings(ChildScene);
        }

        // ---- authoring helpers ---------------------------------------------------------------------------------

        // A collider-only static box (no Rigidbody2D) — the substrate's static-body fallback bakes it, exactly as the
        // gate fixtures' static world is built.
        static GameObject AddStaticBox(Vector2 center, Vector2 size, string name)
        {
            var go = new GameObject(name);
            go.transform.position = new Vector3(center.x, center.y, 0f);
            var box = go.AddComponent<BoxCollider2D>();
            box.size = size;
            return go;
        }

        // A long thin static box rotated to form a ramp, its high (left) end butted at the lip (lipX, lipY) so its top
        // surface ascends to the right at slopeDeg. The character climbs it from the lip.
        static GameObject AddRamp(float lipX, float lipY, float lengthAlong, float slopeDeg, string name)
        {
            var go = new GameObject(name);
            // Centre the ramp so its top-left corner is at the lip, then rotate about that lip point.
            go.transform.position = new Vector3(lipX + lengthAlong * 0.5f, lipY - 0.5f, 0f);
            var box = go.AddComponent<BoxCollider2D>();
            box.size = new Vector2(lengthAlong, 1f);
            go.transform.RotateAround(new Vector3(lipX, lipY, 0f), Vector3.forward, slopeDeg);
            return go;
        }

        static void AddCharacter(Vector3 position)
        {
            var go = new GameObject("Character");
            go.transform.position = position;

            var auth = go.AddComponent<CharacterController2DAuthoring>();
            var props = AuthoringKinematicCharacterProperties2D.GetDefault();
            props.MaxGroundedSlopeAngle = MaxSlopeDeg;
            auth.CharacterProperties = props;
            // Box proxy (1x1): step handling holds a stable stand for a box (gate verdict); a circle catches step
            // corners. The body collider matches the proxy.
            auth.ProxyShape = CharacterProxyShape2D.Box;
            auth.ProxyBoxSize = new Unity.Mathematics.float2(2f * CharacterHalf, 2f * CharacterHalf);
            auth.InterpolateRendering = true;

            // Enable step handling so the character mounts the low step. CharacterWidthForStepGroundingCheck = box
            // width.
            var step = auth.StepAndSlopeHandling;
            step.StepHandling = true;
            step.MaxStepHeight = MaxStepHeight;
            step.CharacterWidthForStepGroundingCheck = 2f * CharacterHalf;
            auth.StepAndSlopeHandling = step;

            // Mark it as the sample's character (the sample solve drives it, NOT the package default tag).
            go.AddComponent<SideScrollerCharacterAuthoring>();
        }

        static void AddPushableCrate(Vector2 position, Vector2 size, float mass, string name)
        {
            var go = new GameObject(name);
            go.transform.position = new Vector3(position.x, position.y, 0f);

            var body = go.AddComponent<PhysicsBody2DAuthoring>();
            body.BodyType = PhysicsBody2DMotionType.Dynamic;
            body.UseAutoMass = false;
            body.Mass = mass;
            body.GravityScale = 1f; // rests on the floor; a real crate that the character shoves around.

            var shape = go.AddComponent<PhysicsShape2DAuthoring>();
            shape.Kind = PhysicsShape2DKind.Box;
            shape.BoxSize = new Unity.Mathematics.float2(size.x, size.y);
            shape.Density = 1f;

            go.AddComponent<SideScrollerPushableAuthoring>();
        }

        static void AddMovingPlatform(Vector2 center, Vector2 size, float halfExtentX, float speedX, string name)
        {
            var go = new GameObject(name);
            go.transform.position = new Vector3(center.x, center.y, 0f);

            var body = go.AddComponent<PhysicsBody2DAuthoring>();
            body.BodyType = PhysicsBody2DMotionType.Kinematic; // driven by MovePosition; never falls.

            var shape = go.AddComponent<PhysicsShape2DAuthoring>();
            shape.Kind = PhysicsShape2DKind.Box;
            shape.BoxSize = new Unity.Mathematics.float2(size.x, size.y);

            var mover = go.AddComponent<SideScrollerMovingPlatformAuthoring>();
            mover.TravelHalfExtentX = halfExtentX;
            mover.SpeedX = speedX;
        }

        static void RegisterSceneInBuildSettings(string scenePath)
        {
            var scenes = new List<EditorBuildSettingsScene>(EditorBuildSettings.scenes);
            if (scenes.Exists(s => s.path == scenePath))
            {
                return;
            }

            scenes.Add(new EditorBuildSettingsScene(scenePath, true));
            EditorBuildSettings.scenes = scenes.ToArray();
        }
    }
}
